// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmkglvrlsnhtaencgpns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNta2dsdnJsc25odGFlbmNncG5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTY0NTksImV4cCI6MjA3MTEzMjQ1OX0.S1x5BPtWjxq62-M8r-wFaFt7X_TZlKfzQDnxk-aCAb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});